name: dynamicscontrol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  - matplotlib==2.2.2
  - numpy==1.14.3
  - scipy==1.1.0
  - sympy==1.1.1
  - control==0.8.0
  - pandas=0.23.0
  - keras=2.2.4
  - scikit-learn==0.19.1
  - pytest==3.6.0
  - jupyter==1.0.0
  - ipywidgets==7.2.1
  - pytest-xdist
  - xlrd==1.1.0
